config/routes.rb
Trolley::Application.routes.draw do
  devise_for :users
  resources :users

  resources :assets do
    collection do
      match "search", :as => :search
    end

    member do
      get "download", :as => :download
    end
  end

  root :to => "assets#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role?(:admin)
      can :manage, :all
    end
  end
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  belongs_to :user

  validates_presence_of :name

  attr_accessible :name, :description, :tag_list, :file

  acts_as_taggable
  has_attached_file :file,
    :url => "/assets/:id_partition/:style_:basename.:extension",
    :path => ":rails_root/public/assets/:id_partition/:style_:basename.:extension",
    :styles => { :medium => [ "400x300#", :jpg ], :thumb => [ "200x150#", :jpg ] }

  before_post_process :check_file_type_for_processing
  before_create :set_identifier

  searchable do
    integer :id
    text :name
    text :tags do
      tags.map { |tag| tag.name }
    end
  end

  def to_param
    "#{id}-#{name.downcase.parameterize}"
  end

  def related(tags)
    Asset.search {
      keywords(tags)
      # TODO: Figure out why this is causing errors.
      # RSolr::RequestError (Solr Response: For_input_string_23882343507840__javalangNumberFormatException_For_input_string_23882343507840
      # without(:id).any_of([ self.id ])
      paginate(:per_page => 8, :page => 1)
    }.results
  end

private

  def check_file_type_for_processing
    file.content_type.include?("image") && file.content_type != "image/vnd.adobe.photoshop"
  end

  def set_identifier
    self.identifier ||= Digest::SHA2.hexdigest("#{name}-#{file_file_name}-#{Time.now}")
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users

  attr_accessible :name

  def self.sanitize role
    role.to_s.humanize.split(" ").each{ |word| word.capitalize! }.join(" ")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :token_authenticatable,
          :recoverable, :rememberable, :trackable,
          :confirmable, :validateable

  has_many :assets
  has_and_belongs_to_many :roles

  attr_accessible :email, :password, :password_confirmation, :role_ids, :remember_me

  def role?(role)
    !!self.roles.find_by_name(Role.sanitize(role))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

private

  def authorize_admin!
    unless current_user.role?(:admin)
      redirect_to(root_path)
    end
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_asset, :except => [ :index, :search, :new, :create ]
  before_filter :format_tag_list, :only => [ :create, :update ]

  respond_to :html, :json

  def index
    @assets = Asset.order("created_at DESC").paginate(:per_page => 20, :page => params[:page])
    respond_with(@assets, :include => :tags, :except => :file)
  end

  def search
    @assets = Asset.search { 
      keywords(params[:q])
      paginate(:per_page => 20, :page => params[:page])
    }.results
    respond_with(@assets, :include => :tags, :except => :file)
  end

  def show
    @asset = Asset.find(params[:id])
    @related_assets = @asset.related(@asset.tags.join(" "))
  end

  def download
    send_file(@asset.file.path, :filename => @asset.file.original_filename, :type => @asset.file.content_type)
  end

  def new
    @asset = Asset.new
  end

  def create
    @asset = current_user.assets.new(params[:asset])
    if @asset.save
      redirect_to(@asset, :notice => "Asset creation successful")
    else
      render(:new)
    end
  end

  def edit
  end

  def update
    if @asset.update_attributes(params[:asset])
      redirect_to(@asset, :notice => "Asset successfully updated")
    else
      render(:edit)
    end
  end

  def destroy
    @asset.destroy
    redirect_to(assets_path, :notice => "Asset successfully deleted")
  end

private

  def find_asset
    @asset = Asset.find(params[:id])
  end

  def format_tag_list
    if params[:asset][:tag_list]
      params[:asset][:tag_list] = params[:asset][:tag_list].join(",")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_admin!
  before_filter :find_user, :only => [ :show, :edit, :update, :destroy ]

  def index
    @users = User.paginate(:per_page => 25, :page => params[:page])
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to(users_path, :notice => "User successfully created")
    else
      render(:new)
    end
  end

  def edit
  end

  def update
    @user.attributes = params[:user]
    if @user.save
      redirect_to(users_path, :notice => "User successfully update")
    else
      render(:edit)
    end
  end

  def destroy
    @user.destroy
    redirect_to(users_path, :notice => "User succesully deleted")
  end

private

  def find_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_messages(flash)
    %w(notice warning error).collect { |message|
      unless flash[message.to_sym].blank?
        content_tag(:p, flash[message.to_sym], :class => "flash " + message)
      end
    }.join
  end

  def display_tags(tags, options = {})
    options[:tagged_with] ||= false

    tags = tags.collect { |t| link_to(t.name, search_assets_path(:q => t.name)) }.join(", ")
    content_tag("p", :class => "tags") do
      if options[:tagged_with]
        "<span>Tagged With:</span> #{tags}"
      else
        tags
      end
    end
  end

  def thumbnail_uri(asset, size)
    if File.exists?(asset.file.path(size))
      image_tag(asset.file.url(size))
    else
      image_tag("/images/default/#{size}.png")
    end
  end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_asset.html.haml
.grid_3
  .asset-summary
    = link_to(thumbnail_uri(asset, :thumb), asset_path(asset))
    = display_tags(asset.tags)

app/views/assets/_form.html.haml
= semantic_form_for(@asset, :html => { :multipart => true }) do |f|
  = f.semantic_errors
  = f.inputs(:name, :description)
  = f.input(:file, :as => :file)
  .tagbox.tags.group
    = @asset.tags.collect{ |t| t.name }.join(",")
  = f.buttons

- content_for(:javascript) do
  :javascript
    $(function() {
      $(".tagbox.tags").tagbox({
        seperator: /,/,
        name: "asset[tag_list][]"
      });
    });

app/views/assets/edit.html.haml
.grid_12
  = render(:partial => "form")

app/views/assets/index.html.haml
- unless @assets.empty?
  .group= render(@assets)
  .pagination= will_paginate(@assets)

- else
  .grid_12
    %p There are no assets.

app/views/assets/new.html.haml
.grid_12
  = render("form")

app/views/assets/search.html.haml
- unless @assets.empty?
  .grid_6
    %h2= "Results for '#{params[:q]}'"
  .grid_6.text-right
    %p= "#{@assets.total_entries} Total Results"
  .clear

  .group= render(@assets)
  .pagination= will_paginate(@assets)
- else
  .grid_12
    %h2= "Results for '#{params[:q]}'"
    %p= "No assets match '#{params[:q]}'"

app/views/assets/show.html.haml
.grid_12
  .right.text-center
    .asset-download
      = thumbnail_uri(@asset, :medium)
    %p= link_to("Download Asset (#{number_to_human_size(@asset.file.size)})", download_asset_path(@asset), :class => "button")
    %p.small
      = link_to("Edit Asset", edit_asset_path(@asset))
      |
      = link_to("Delete Asset", asset_path(@asset), :method => :delete)

  %ul.metadata
    %li= raw("<span>File Name:</span> #{@asset.file.original_filename}")
    %li= raw("<span>Created At:</span> #{@asset.created_at.to_s(:long)}")
    %li= raw("<span>Updated At:</span> #{@asset.created_at.to_s(:long)}")
    %li= display_tags(@asset.tags, :tagged_with => true)

  = simple_format(@asset.description)

- unless @related_assets.empty?
  #related-assets
    .grid_12
      %h3 Related Assets
    = render(@related_assets)

app/views/layouts/application.html.haml
!!! 5

%html
%head
  %meta{ "http-equiv" => "Content-Type", :content => "text/html; charset=utf-8" }
  %meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }
  %title Trolley - Asset Manager
  = csrf_meta_tag
  = include_stylesheets(:main, :media => "all")

%body
  #header.group
    .container_12
      .grid_9
        %ul#navigation
          - if user_signed_in?
            %li= link_to("Browse Assets", root_path)
            %li= link_to("Upload New Asset", new_asset_path)
            - if current_user.role?("Admin")
              %li= link_to("Manage Users", users_path)
            %li= raw("Signed in as #{current_user.email} (#{link_to("Logout", destroy_user_session_path)})")
          - else
            %li Trolley - Asset Manager

      .grid_3.text-right
        - if user_signed_in?
          = form_tag(search_assets_path) do |f|
            = text_field_tag("q", "", :placeholder => "Search for assets...")

  #content.group
    .container_12
      - unless flash_messages(flash).blank?
        .grid_12
          #flash_messages= raw(flash_messages(flash))

      = yield

  #footer
    .container_12
      .grid_6
        %p Trolley - Asset Manager

      .grid_6.text-right
        %p= link_to("https://github.com/sniperd/trolley", "https://github.com/sniperd/trolley", :target => "_blank")

  = include_javascripts(:common)
  = yield(:javascript)

app/views/users/_form.html.haml
= semantic_form_for(@user) do |f|
  = f.inputs(:email, :password, :password_confirmation)
  = f.input(:role_ids, :as => :check_boxes, :collection => Role.all)
  = f.buttons

app/views/users/edit.html.haml
.grid_12
  = render("form")

app/views/users/index.html.haml
.grid_12
  .right= link_to("Add New User", new_user_path, :class => "button")

  %h2 Manage Users

  %table
    %tr
      %th Email
      %th.text-center Number of Assets
      %th Roles
      %th

    - @users.each do |user|
      %tr
        %td= link_to(user.email, user_path(user))
        %td.text-center= user.assets.count
        %td= user.roles.collect { |r| r.name }.join(", ")
        %td.text-right= link_to("Edit User", edit_user_path(user))

app/views/users/new.html.haml
.grid_12
  = render("form")

app/views/users/show.html.haml
.grid_12
  %h2= "User #{@user.email}"